version: '3.8'
services:
  client_dev:
    depends_on:
      - server_dev
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.local
      
  client_prod:
    build: 
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env

  server_dev:
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.local


  server_prod:
    build: 
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
      
      
    