FROM node:20-alpine

WORKDIR /app

RUN npm install -g prisma

COPY package*.json ./

RUN npm install

COPY ./prisma ./prisma

RUN npx prisma generate

COPY . .

EXPOSE 4000

CMD ["npm", "run", "start:dev"]
